spring:
  application:
    name: gateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:8761/eureka/,http://eureka-server-1:8762/eureka/,http://eureka-server-3:8763/eureka/
logging:
  level:
    root: DEBUG