spring:
  application:
    name: compute-service
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:8761/eureka/,http://eureka-server-1:8762/eureka/,http://eureka-server-3:8763/eureka/