spring:
  application:
    name: zuul
server:
  port: 5555
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: DEBUG
#  routes:
#    compute-service:
#      path: /compute/*
#      serviceId: compute-service
#    product-service:
#      path: /products/*
#      serviceId: product-service
