spring:
  application:
    name: zuul
server:
  port: 5555
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:8761/eureka/,http://eureka-server-2:8762/eureka/,http://eureka-server-3:8763/eureka/
logging:
  level:
    root: DEBUG
zuul:
  routes:
    sidecar-client:
      path: /client/**
      serviceId: sidecar
      stripPrefix: false
      sensitiveHeaders:
    sidecar-server:
      path: /server/**
      serviceId: sidecar
      stripPrefix: false
      sensitiveHeaders:
    compute-service:
      path: /compute-service/**
      serviceId: compute-service
      stripPrefix: true
      sensitiveHeaders:
    product-service:
      path: /product/**
      serviceId: product-service
      stripPrefix: true
      sensitiveHeaders: