spring:
  application:
    name: sidecar
server:
  port: 5678
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:8761/eureka/,http://eureka-server-1:8762/eureka/,http://eureka-server-3:8763/eureka/
sidecar:
  port: 3000
  health-uri: http://localhost:3000/health
#zuul:
#  routes:
#    product-service:
#      path: /product-service/**
#      serviceId: product-service
#      stripPrefix: true
#      sensitiveHeaders: