server:
  port: 8762
eureka:
  instance:
    hostname: eureka-server-2
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server-1:8761/eureka/,http://eureka-server-3:8763/eureka/